version: '3.3'
services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false

    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.1
    container_name: logstash
    environment:
      - cluster.name=s-docker-cluster
      - node.name=logstash
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - es8
    ports:
      - 9600:9600
    networks:
      - elastic

  kib8:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200/

    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - es8
volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
